name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible-lint
      - name: Run linter
        run: |
          ansible-lint setup.yml

  execute-playbook:
    env:
      IS_GITHUB_CI: 1
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible dconf-cli
      - name: Run playbook
        run: |
          ansible-playbook setup.yml
      - name: Run playbook second time and verify no changed tasks
        run: |
          ansible-playbook setup.yml 2>&1 | tee /tmp/ansible-playbook.log
          tail -2 /tmp/ansible-playbook.log | grep -q 'changed=0.*failed=0'
